// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyIQjV7Vmygu0MDTI5qMCcHDDbG1_n4qQ',
    appId: '1:352913613282:web:28dbe220c88c3c7b8e19bb',
    messagingSenderId: '352913613282',
    projectId: 'smartcloud-f0dcf',
    authDomain: 'smartcloud-f0dcf.firebaseapp.com',
    storageBucket: 'smartcloud-f0dcf.firebasestorage.app',
    measurementId: 'G-ZF507KCN97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFwOefB4NbCiNWkZkuLUigh1-Lcg1LlSw',
    appId: '1:352913613282:android:817cde6dbfa058338e19bb',
    messagingSenderId: '352913613282',
    projectId: 'smartcloud-f0dcf',
    storageBucket: 'smartcloud-f0dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2tdrVRrusMxWyCWPfGhfuFHG1nTQ-Nrc',
    appId: '1:352913613282:ios:d13e4ed3139975268e19bb',
    messagingSenderId: '352913613282',
    projectId: 'smartcloud-f0dcf',
    storageBucket: 'smartcloud-f0dcf.firebasestorage.app',
    iosBundleId: 'com.example.smartCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2tdrVRrusMxWyCWPfGhfuFHG1nTQ-Nrc',
    appId: '1:352913613282:ios:d13e4ed3139975268e19bb',
    messagingSenderId: '352913613282',
    projectId: 'smartcloud-f0dcf',
    storageBucket: 'smartcloud-f0dcf.firebasestorage.app',
    iosBundleId: 'com.example.smartCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyIQjV7Vmygu0MDTI5qMCcHDDbG1_n4qQ',
    appId: '1:352913613282:web:55f7b9f49d53b19a8e19bb',
    messagingSenderId: '352913613282',
    projectId: 'smartcloud-f0dcf',
    authDomain: 'smartcloud-f0dcf.firebaseapp.com',
    storageBucket: 'smartcloud-f0dcf.firebasestorage.app',
    measurementId: 'G-CJTGZZYLZY',
  );
}
